# 适用QuantumultX Unlock App

hostname = ap*.intsig.net, ap*.intsig.net, api.vuevideo.net, vsco.co, api.revenuecat.com, bmall.camera360.com, commerce-i18n-api.faceu.mobi, commerce-api.faceu.mobi, api.xiuxiu.meitu.com, api.meiyan.com, license.pdfexpert.com, biz.caiyunapp.com, 

# -- BY NobyDa --

# 扫描全能王CamScanner pro    ap*.intsig.net 
^https:\/\/(api|api-cs)\.intsig\.net\/purchase\/cs\/query_property\? url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/CamScanner.js
# PicsArt美易 pro   ap*.intsig.net 
^https:\/\/api\.(picsart|meiease)\.c(n|om)\/users\/show\/me\.json url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/PicsArt.JS
# VUE Vlog 解锁高级功能 (需登录)    api.vuevideo.net  
^https:\/\/api\.vuevideo\.net\/api\/v1\/(users\/.+\/profile|subtitle\/prepare) url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/VUE.js
# VSCO 解锁高级特权    vsco.co, api.revenuecat.com
^https:\/\/(api\.revenuecat\.com\/v\d\/subscribers|vsco\.co\/api\/subscriptions\/\d\.\d\/user-subscriptions)\/ url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/vsco.js
# MIX 解锁高级特权 (需恢复购买)  bmall.camera360.com
https?:\/\/bmall\.camera360\.com\/api\/mix\/recovery url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/MIX.js

#-- BY songyangzz --

# ulike轻颜相机 commerce-i18n-api.faceu.mobi, commerce-api.faceu.mobi
^https:\/\/commerce-.*api\.faceu\.mobi\/commerce\/v1\/subscription\/user_info url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/ulike.js

# -- BY 黑黑酱 --  

# 美图秀秀 v9.0.51版本 api.xiuxiu.meitu.com  
^https:\/\/api\.xiuxiu\.meitu\.com\/v1\/user\/show\.json url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/mtxx.js
# 美颜相机 v9.6.20版本）api.meiyan.com
^https:\/\/api\.meiyan\.com\/vip\/user_info url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/Meiyanxiangji.js

# -- BY langkhach270389 --

# PdfExpert vip  license.pdfexpert.com
^https:\/\/license\.pdfexpert\.com\/api\/.+\/subscription\/(refresh$|check$) url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/PdfExpert.js

# -- BY Tartarus2014 --

# 彩云天气pro vip   biz.caiyunapp.com
https?:\/\/biz\.caiyunapp\.com\/(membership_rights|v2\/user) url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/CaiYun.js
 
