#-- BY langkhach270389 --
# Unlock Buy Apple   
hostname = buy.itunes.apple.com

^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/Buy-itunes.js
