#-- BY Xirou --
# Picsew vip  
hostname buy.itunes.apple.com
^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt url script-response-body https://raw.githubusercontent.com/tutuh/script/master/JS/Picsew.js
